/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.utl.dsm.mongoView;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static org.utl.dsm.mongoView.Insertar.crearConexion;

/**
 *
 * @author pc
 */
public class Actualizar extends javax.swing.JPanel {

    DB db;
    BasicDBObject backup;
    DBCollection collect;

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        actualizarTabla();

        jTableActualizar.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int selectedRow = jTableActualizar.getSelectedRow();
                    if (selectedRow != -1) {
                        nombreActualizar.setText(jTableActualizar.getValueAt(selectedRow, 0).toString());
                        apellidoPActualizar.setText(jTableActualizar.getValueAt(selectedRow, 1).toString());
                        edadActualizar.setText(jTableActualizar.getValueAt(selectedRow, 2).toString());
                        nacionalidadActualizar.setText(jTableActualizar.getValueAt(selectedRow, 3).toString());

                        docbackup();
                    }
                }
            }
        });
    }

    public static MongoClient crearConexion() {
        MongoClient mongo = null;
        mongo = new MongoClient("localhost", 27017);

        return mongo;
    }

    private void actualizarTabla() {
        // Obtén la conexión y la colección
        MongoClient mongo = crearConexion();
        DB db = mongo.getDB("pruebaMongo");
        collect = db.getCollection("usuarios");

        // Realiza la consulta a la base de datos
        DBCursor cursor = collect.find();

        // Obtén el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) jTableActualizar.getModel();

        // Limpia el modelo actual
        model.setRowCount(0);

        // Itera sobre los resultados y añade las filas a la tabla
        while (cursor.hasNext()) {
            DBObject row = cursor.next();
            String nombre = (String) row.get("nombre");
            String apellidoP = (String) row.get("apellidoP");
            Object edadObject = row.get("edad");
            String edad = (edadObject != null) ? edadObject.toString() : "";
            String nacionalidad = (String) row.get("nacionalidad");

            // Agrega la fila al modelo
            model.addRow(new Object[]{nombre, apellidoP, edad, nacionalidad});
        }

        // Cierra el cursor
        cursor.close();

        viewMongoCRUD metodo = new viewMongoCRUD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActualizar = new javax.swing.JTable();
        edadActualizar = new javax.swing.JTextField();
        nacionalidadActualizar = new javax.swing.JTextField();
        apellidoPActualizar = new javax.swing.JTextField();
        nombreActualizar = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(453, 364));

        jTableActualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "ApellidoPaterno ", "Edad", "Nacionalidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableActualizarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableActualizar);

        btnActualizar.setText("actualizar");
        btnActualizar.setAlignmentX(14.0F);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Edad");

        jLabel4.setText("Nacionalidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoPActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(edadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nacionalidadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoPActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        updateDocument();
        actualizarTabla();
        cleanInputs();

    }//GEN-LAST:event_btnActualizarActionPerformed

    public void updateDocument() {
        MongoClient mongo = crearConexion();
        DB db = mongo.getDB("pruebaMongo");
        collect = db.getCollection("usuarios");
        BasicDBObject updateDocument = new BasicDBObject();
        updateDocument.append("nombre", nombreActualizar.getText());
        updateDocument.append("apellidoP", apellidoPActualizar.getText());
        updateDocument.append("edad", edadActualizar.getText());
        updateDocument.append("nacionalidad", nacionalidadActualizar.getText());

        collect.findAndModify(backup, updateDocument);
    }

    private void jTableActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableActualizarMouseClicked
        int fila = jTableActualizar.rowAtPoint(evt.getPoint());
        nombreActualizar.setText(jTableActualizar.getValueAt(fila, 0).toString());
        apellidoPActualizar.setText(jTableActualizar.getValueAt(fila, 1).toString());
        edadActualizar.setText(jTableActualizar.getValueAt(fila, 2).toString());
        nacionalidadActualizar.setText(jTableActualizar.getValueAt(fila, 3).toString());
        docbackup();
    }//GEN-LAST:event_jTableActualizarMouseClicked

    public void docbackup() {
        backup = new BasicDBObject();
        backup.put("nombre", nombreActualizar.getText());
        backup.put("apellidoP", apellidoPActualizar.getText());
        backup.put("edad", edadActualizar.getText());
        backup.put("nacionalidad", nacionalidadActualizar.getText());
    }
    
    public void cleanInputs() {
        nombreActualizar.setText("");
        apellidoPActualizar.setText("");
        edadActualizar.setText("");
        nacionalidadActualizar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoPActualizar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JTextField edadActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableActualizar;
    private javax.swing.JTextField nacionalidadActualizar;
    private javax.swing.JTextField nombreActualizar;
    // End of variables declaration//GEN-END:variables
}
